[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
dist-name = "docopt-parser"
module = "docopt_parser"
author = "Anders Ingemann"
author-email = "anders@ingemann.de"
home-page = "https://github.com/andsens/docopt-parser"
description-file = "README.adoc"
classifiers = [
  "Topic :: Utilities",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.5",
  "Programming Language :: Python :: 3.6",
  "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.5"
requires = ["docopt", "termcolor", "parsec", "pyyaml"]

[tool.flit.sdist]
include = ["docopt_parser/version.py"]
exclude = ["tests", "pytest.ini", ".*"]

[tool.flit.metadata.requires-extra]
test = [
  "flake8",
  "pytest",
  "pytest-xdist",
  "pytest-flake8",
  'hypothesis',
  'docopt'
]
