from collections import namedtuple

Multiple = namedtuple('Multiple', ['atom'])
Long = namedtuple('Long', ['name', 'arg'])
Short = namedtuple('Short', ['name', 'arg'])
Shorts = namedtuple('Shorts', ['name', 'arg'])
Command = namedtuple('Command', ['name'])
Choice = namedtuple('Choice', ['items'])
Sequence = namedtuple('Sequence', ['items'])
Optional = namedtuple('Optional', ['item'])
Argument = namedtuple('Argument', ['name'])
OptionsShortcut = namedtuple('OptionsShortcut', [])
OptionLine = namedtuple('OptionLine', ['ident', 'default'])
Options = namedtuple('Options', 'lines')
DocoptAst = namedtuple('DocoptLang', ['usage', 'options'])
