name: Lint, typecheck, test

on:
  push:
    branches: ['*']
    tags:
    - '*'
    - '!v*' # Don't run on version tags, instead the release workflow will include this file and call the build step
  workflow_call: {}
  pull_request:
    branches: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the project
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Cache virtualenv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv
    - name: Install dependencies
      run: .devcontainer/post.sh
    - name: Lint with flake8
      run: |
        # error out if there are Python syntax errors or undefined names
        .venv/bin/flake8 docopt_parser --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        .venv/bin/flake8 docopt_parser --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  typecheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the project
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Cache virtualenv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv
    - name: Install dependencies
      run: .devcontainer/post.sh
    - name: Typecheck with pyright
      run: .venv/bin/pyright docopt_parser
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
    - name: Checkout the project
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache virtualenv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv
    - name: Install dependencies
      run: .devcontainer/post.sh
    - name: Cache hypothesis DB
      uses: actions/cache@v4
      with:
        path: .hypothesis
        key: hypothesis
    - name: Test with pytest
      run: .venv/bin/pytest
